set(CMAKE_C_VERBOSE_FLAG "-v")

set(CMAKE_C_FLAGS_INIT "")
set(CMAKE_C_FLAGS_DEBUG_INIT "-g")
set(CMAKE_C_FLAGS_MINSIZEREL_INIT "-o+space -DNDEBUG")
set(CMAKE_C_FLAGS_RELEASE_INIT "-o -g -DNDEBUG")
set(CMAKE_C_FLAGS_RELWITHDEBINFO_INIT "-o -g -DNDEBUG")

set(CMAKE_C_COMPILE_OBJECT
    "<CMAKE_C_COMPILER> <FLAGS> -o<OBJECT> -c <SOURCE>")

set(CMAKE_C_LINK_EXECUTABLE
    "<CMAKE_C_COMPILER> <FLAGS> <CMAKE_C_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o<TARGET> <LINK_LIBRARIES>")
