set(__COMPILER_GNU 1)
set(CMAKE_D_VERBOSE_FLAG "-v")
set(CMAKE_D_COMPILE_OPTIONS_PIC "-fPIC")
set(CMAKE_D_COMPILE_OPTIONS_PIE "-fPIE")
set(CMAKE_SHARED_LIBRARY_D_FLAGS "-fPIC")
set(CMAKE_SHARED_LIBRARY_CREATE_D_FLAGS "-shared")

set(CMAKE_D_FLAGS_INIT "")
set(CMAKE_D_FLAGS_DEBUG_INIT "-g -fdebug")
set(CMAKE_D_FLAGS_MINSIZEREL_INIT "-frelease -O3")
set(CMAKE_D_FLAGS_RELEASE_INIT "-frelease -O3 -finline")
set(CMAKE_D_FLAGS_RELWITHDEBINFO_INIT "-frelease -O3 -finline -g")

set(CMAKE_D_CREATE_PREPROCESSED_SOURCE "<CMAKE_D_COMPILER> <FLAGS> -E <SOURCE> > <PREPROCESSED_SOURCE>")
set(CMAKE_D_CREATE_ASSEMBLY_SOURCE "<CMAKE_D_COMPILER> <DEFINES> <FLAGS> -S <SOURCE> -o <ASSEMBLY_SOURCE>")
#set(CMAKE_INCLUDE_SYSTEM_FLAG_D "-isystem -I")
set(CMAKE_DEPFILE_FLAGS_D "-fmake-deps=<DEPFILE>")
set(CMAKE_NINJA_DEPTYPE_D "gcc")

set(CMAKE_INCLUDE_FLAG_D "-I")
set(CMAKE_INCLUDE_FLAG_D_SEP "")

set(CMAKE_D_VERSION_FLAG "-fversion=")
set(CMAKE_D_DEBUG_FLAG "-fdebug=")
set(CMAKE_D_TEXT_INCLUDE_FLAG "-J")
set(CMAKE_D_UNITTEST_FLAG "-funittest")
# GDC doesn't seem to support -cov
# GDC doesn't seem to support -main
set(CMAKE_D_DDOC_FILE_FLAG "-fdoc-file=")
set(CMAKE_D_DDOC_MACRO_FLAG "-fdoc-inc=")
set(CMAKE_D_DEPS_FILE_FLAG "-fdeps=")
set(CMAKE_D_PRINT_DEPS_FLAG "-fdeps")
set(CMAKE_D_NO_OUTPUT_FLAG -S -o ${CMAKE_CURRENT_BINARY_DIR}/CMakeFiles/cmake_gdc_garbage)
set(CMAKE_D_JSON_FILE_FLAG "-fXf=")

set(CMAKE_D_COMPILE_OBJECT
    "<CMAKE_D_COMPILER> <DEFINES> <FLAGS> -o <OBJECT> -c <SOURCE>")
set(CMAKE_D_CREATE_SHARED_LIBRARY
    "<CMAKE_D_COMPILER> <CMAKE_SHARED_LIBRARY_D_FLAGS> <LANGUAGE_COMPILE_FLAGS> <LINK_FLAGS> <CMAKE_SHARED_LIBRARY_CREATE_D_FLAGS> <SONAME_FLAG><TARGET_SONAME> -o <TARGET> <OBJECTS> <LINK_LIBRARIES>")
set(CMAKE_D_LINK_EXECUTABLE
    "<CMAKE_D_COMPILER> <FLAGS> <CMAKE_D_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")
set(CMAKE_D_ARCHIVE_CREATE "<CMAKE_AR> cr <TARGET> <LINK_FLAGS> <OBJECTS>")
set(CMAKE_D_ARCHIVE_APPEND "<CMAKE_AR> r  <TARGET> <LINK_FLAGS> <OBJECTS>")
set(CMAKE_D_ARCHIVE_FINISH "<CMAKE_RANLIB> <TARGET>")
