include(Platform/Linux-GNU)
__linux_compiler_gnu(D)

set(CMAKE_D_COMPILE_OPTIONS_PIC "-fPIC")
set(CMAKE_D_COMPILE_OPTIONS_PIE "-fPIE")
set(CMAKE_SHARED_LIBRARY_D_FLAGS "-fPIC")

set(CMAKE_SHARED_LIBRARY_CREATE_D_FLAGS "-shared")
set(CMAKE_SHARED_LIBRARY_RUNTIME_D_FLAG "-Wl,-rpath,")
set(CMAKE_SHARED_LIBRARY_RUNTIME_D_FLAG_SEP ":")
set(CMAKE_SHARED_LIBRARY_RPATH_LINK_D_FLAG "-Wl,-rpath-link,")
set(CMAKE_SHARED_LIBRARY_SONAME_D_FLAG "-Wl,-soname,")
set(CMAKE_EXE_EXPORTS_D_FLAG "-Wl,--export-dynamic")
