#!/bin/bash
#
# DDeps - D Dependency Scanner for CMake
# Copyright 2014 Trent Forkert
#
# Distributed under the OSI-approved BSD License (the "License");
# see accompanying file Copyright.txt for details.
#
# This software is distributed WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the License for more information.
#

set -eu

# This script pulls the character entities from W3C,
# and produces a C++ method to translate the identifier
# between the ampersand and the semicolon into a unicode
# codepoint

# This is needed because D allows HTML5 entities in strings such that:
#   "\&UnderBar;" == "_"
# We need to parse them in case someone does import("hello\&UnderBar;world.txt")
# or similar. We don't do CTFE (compile time function evaluation),
# so the only text imports we can get are those with string literals,
# but doing this allows DDeps to support the rare case in which this is
# used in that way.

# This makes some assumptions about the formatting of the W3C JSON file,
# but all that matters is that it works.

# The first line after "curl ..." removes lines that don't contain a ";"
# The next line transforms each JSON mapping to a line of C++
# The next three lines escape backslashes, double quotes, and newlines.
# Everything else until the "endif" closes the method and header
# Last line converts the remaining escapes into C \xFF style UTF-8 escapes
# Finally writing this all to the header

echo -e "\
/* This file was generated by ${0} */
/* DO NOT EDIT! */
#ifndef ddeps_entities_h
#define ddeps_entities_h
#include <string>

// Translate HTML5 character entities into UTF-8 escapes
// ent is the name between the ampersand and the semicolon
std::string translateEntity(std::string const& ent)
{
$( curl "http://www.w3.org/TR/html5/entities.json" \
| grep ";" \
| sed -r 's/"&([^;]+);".*: "([^"]+)" \},?/if(ent=="\1") return "\2";/g' \
| sed -r 's/\u005C/\\\\/g' \
| sed -r 's/\u000A/\\n/g' \
| sed -r 's/\u0022/\\"/g' \
)

  // If an invalid entity was given, just return empty string
  return \"\";
}

#endif" | uni2ascii -a7 > ddeps_entities.h
